site_name: NearIT Xamarin
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
extra_javascript : ["js/extra.js"]
pages:
    - 'Getting started' : 'index.md'
    - 'iOS' :
        - 'Setup' : 'ios/setup.md'
        - 'Notification Setup' : 'ios/setup-notifications.md'
        - 'Location Based Notifications' : 'ios/location-based-notifications.md'
        - 'Push Notification' : 'ios/push-notifications.md'
        - 'In-app Content' : 'ios/handle-content.md'
        - 'User Profiling' : 'ios/user-profiling.md'
    - 'Android' :
        - 'Setup' : 'android/setup.md'
        - 'Location Based Notifications' : 'android/location-based-notifications.md'
        - 'Push Notifications' : 'android/push-notifications.md'
        - 'In-app Content' : 'android/in-app-content.md'
        - 'User Profiling' : 'android/user-profiling.md'

